### ISSUE TITLE
Use db.contains to check if at least one element matches a query

### ISSUE THREAD

**Issue by alchemyst** [reinhardfechter/FlexPVCModel#12]
There are quite a few places in the code where you have `check = db.query()` and later `if len(check) == 0` or other way around. All these checks can be made faster by using `db.contains`.

**Comment by reinhardfechter** [comment]
How do I check whether a db is empty or not? at the moment I use `check = db.all()` and then `if check == 0`

**Comment by alchemyst** [comment]
You can simply do `if not db:`.
